import { schedule } from 'node-cron';
import nodemailer from 'nodemailer';
import { query } from '../config/db.js';
import * as reportsService from '../modules/reports/reports.service.js';
import { markRan } from '../modules/reports/schedules.service.js';
import { logger } from '../config/logger.js';
import { env } from '../config/env.js';

function makeTransporter() {
  const { host, port, user, pass, secure } = env.smtp || {};
  if (!host) return null;
  return nodemailer.createTransport({
    host,
    port: port || 587,
    secure: secure || false,
    auth: user ? { user, pass } : undefined,
  });
}

export async function executeSchedule(s) {
  logger.info(`Running scheduled report: ${s.name} (${s.report_type})`);
  try {
    const opId = s.operator_id || null;
    let rows;
    switch (s.report_type) {
      case 'compliance': rows = await reportsService.generateComplianceReport(opId, null, null); break;
      case 'trend':      rows = await reportsService.generateTrendReport(opId, null, null);      break;
      case 'anomaly':    rows = await reportsService.generateAnomalyReport(opId);                break;
      default:           rows = await reportsService.generateOperatorKpiReport(opId, null, null);
    }

    const buffer = reportsService.buildExcelBuffer(rows, s.report_type.toUpperCase());
    const filename = `TNIP_${s.report_type}_Report.xlsx`;

    const recipients = (s.recipients || '').split(',').map((r) => r.trim()).filter(Boolean);
    if (recipients.length) {
      const transporter = makeTransporter();
      if (transporter) {
        await transporter.sendMail({
          from: env.smtp.from || 'TNIP-R Reports <reports@tnipr.gov>',
          to: recipients.join(', '),
          subject: `TNIP-R Automated Report: ${s.name}`,
          html: `<p>Please find attached the automated <strong>${s.report_type}</strong> report: <em>${s.name}</em>.</p>
                 <p>Generated by TNIP-R on ${new Date().toLocaleString()}.</p>`,
          attachments: [{ filename, content: buffer, contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }],
        });
        logger.info(`Report emailed to: ${recipients.join(', ')}`);
      } else {
        logger.warn(`SMTP not configured — skipping email for schedule: ${s.name}`);
      }
    }

    await markRan(s.schedule_id);
    logger.info(`Schedule complete: ${s.name}`);
    return { rows: rows.length, emailed: recipients.length > 0 };
  } catch (err) {
    logger.error(`Schedule failed [${s.name}]: ${err.message}`);
    throw err;
  }
}

export function startReportScheduler() {
  schedule('*/5 * * * *', async () => {
    try {
      const due = await query(
        'SELECT * FROM scheduled_reports WHERE is_active = 1 AND next_run_at <= NOW()',
      );
      if (due.length) logger.info(`Report scheduler: ${due.length} due schedule(s)`);
      for (const s of due) {
        await executeSchedule(s).catch(() => {});
      }
    } catch (err) {
      logger.error(`Scheduler tick error: ${err.message}`);
    }
  });
  logger.info('Report scheduler started — checks every 5 minutes');
}
