import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import operatorRoutes from '../modules/operators/operators.routes.js';
import ingestionRoutes from '../modules/ingestion/ingestion.routes.js';
import counterRoutes from '../modules/counters/counters.routes.js';
import inventoryRoutes from '../modules/inventory/inventory.routes.js';
import sftpRoutes from '../modules/sftp/sftp.routes.js';
import kpiRoutes from '../modules/kpi/kpi.routes.js';
import complianceRoutes from '../modules/compliance/compliance.routes.js';
import dashboardRoutes from '../modules/dashboard/dashboard.routes.js';
import rankingRoutes from '../modules/ranking/ranking.routes.js';
import aiRoutes from '../modules/ai/ai.routes.js';
import reportsRoutes from '../modules/reports/reports.routes.js';
import drivetestRoutes from '../modules/drivetest/drivetest.routes.js';
import usersRoutes from '../modules/users/users.routes.js';
import settingsRoutes from '../modules/settings/settings.routes.js';
import thresholdsRoutes from '../modules/compliance/thresholds.routes.js';
import licensesRoutes from '../modules/licenses/licenses.routes.js';
import auditRoutes from '../modules/audit/audit.routes.js';
import notificationsRoutes from '../modules/notifications/notifications.routes.js';
import anomalyRoutes from '../modules/anomaly/anomaly.routes.js';
import enforcementRoutes from '../modules/enforcement/enforcement.routes.js';
import portalRoutes from '../modules/operator-portal/portal.routes.js';
import disputesRoutes from '../modules/disputes/disputes.routes.js';
import submissionsRoutes from '../modules/submissions/submissions.routes.js';
import obligationsRoutes from '../modules/obligations/obligations.routes.js';
import penaltiesRoutes from '../modules/penalties/penalties.routes.js';
import campaignsRoutes from '../modules/drivetest/campaigns.routes.js';
import gatewayRoutes from '../modules/gateway/gateway.routes.js';
import realtimeRoutes from '../modules/realtime/realtime.routes.js';
import qoeRoutes from '../modules/qoe/qoe.routes.js';
import predictiveRoutes from '../modules/analytics/predictive.routes.js';
import spectrumRoutes from '../modules/spectrum/spectrum.routes.js';
import fieldRoutes from '../modules/field/field.routes.js';
import slaRoutes from '../modules/sla/sla.routes.js';
import fiberRoutes from '../modules/fiber/fiber.routes.js';
import complaintsRoutes from '../modules/complaints/complaints.routes.js';
import complaintAnalyticsRoutes from '../modules/complaint-analytics/complaint-analytics.routes.js';
import regionalCoverageRoutes from '../modules/regional-coverage/regional-coverage.routes.js';
import speedtestRoutes from '../modules/speedtest/speedtest.routes.js';

const router = Router();

router.get('/health', (_req, res) => res.json({ status: 'ok', service: 'tnipr-backend', ts: new Date().toISOString() }));

router.use('/auth', authRoutes);
router.use('/operators', operatorRoutes);
router.use('/ingestion', ingestionRoutes);
router.use('/counters', counterRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/sftp', sftpRoutes);
router.use('/kpis', kpiRoutes);
router.use('/compliance', complianceRoutes);
router.use('/dashboards', dashboardRoutes);
router.use('/rankings', rankingRoutes);
router.use('/ai', aiRoutes);
router.use('/reports', reportsRoutes);
router.use('/drive-tests', drivetestRoutes);
router.use('/users', usersRoutes);
router.use('/settings', settingsRoutes);
router.use('/thresholds', thresholdsRoutes);
router.use('/licenses', licensesRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/anomalies', anomalyRoutes);
router.use('/enforcement', enforcementRoutes);
router.use('/operator-portal', portalRoutes);
router.use('/disputes', disputesRoutes);
router.use('/submissions', submissionsRoutes);
router.use('/obligations', obligationsRoutes);
router.use('/penalties', penaltiesRoutes);
router.use('/dt-campaigns', campaignsRoutes);
router.use('/gateway', gatewayRoutes);
router.use('/realtime', realtimeRoutes);
router.use('/qoe', qoeRoutes);
router.use('/predictive', predictiveRoutes);
router.use('/spectrum', spectrumRoutes);
router.use('/field', fieldRoutes);
router.use('/sla', slaRoutes);
router.use('/fiber', fiberRoutes);
router.use('/complaints', complaintsRoutes);
router.use('/complaint-analytics', complaintAnalyticsRoutes);
router.use('/regional-coverage', regionalCoverageRoutes);
router.use('/speedtest', speedtestRoutes);

export default router;
